### ISSUE TITLE
preventDefault on TouchEnd

### ISSUE THREAD

**Issue by FabienHenon** [zwilias/elm-touch-events#1]
Than you for this package! It has been really helpful for my project.

However, while browsing the source code I noticed a call to `preventDefault` for the `touchend` event.
Is there any reason you call `preventDefault`? I'm asking this because I have a `click` event for a child node and this click event isn't triggered. Whereas, when I disable the `touchend` event it is triggered.
Thus I guess `preventDefault` should be the cause of my issue.
If `preventDefault` is not useful, I may remove it from a fork :)

**Comment by zwilias** [comment]
If I recall correctly, `click` on mobile fires with a 300 ms delay, so I wanted to allow simulating taps with `Touch.onEnd`. But then, if you have both `onClick` and `Touch.onEnd` on a single node, both would fire - first the touch event, then 300 ms later the `click` event. Very annoying.

What I hoped to achieve with the `preventDefault` was to allow having both event on a single node, with `Touch.onEnd` being used to capture taps on mobile without the 300 ms delay, and `onClick` seamlessly working on desktop, since it wouldn't be prevented as there wouldn't be a `touch` event in the first place.

It seems rather funky that a click event on a child node would be prevented by a parent having `preventDefault`, though; I wasn't aware that this was a possibility.

So realistically, I see 2 options:
1.  use `Touch.onEnd (always YourMsg), onClick YourMsg` on the child-node as a cheap-man's "tap on mobile, click on dekstop" behaviour. The caveat being that it would also fire when swiping "into" the node and releasing there. In a sense, this wouldn't be unlike the default button behaviour on iOS which is "on touch up inside".
2. expose a `Touch.onEndWithOptions Options (Touch.Event -> msg)` function, so it can be overridden.

What do you think @FabienHenon ?

**Comment by FabienHenon** [comment]
Thank you for your answer. I understand your point indeed.

I found a solution using your first option.
I used all events on my child node `onEnd, onStart, onMove` and I used a different `Touch.Event` object that the one I use for my swipe, and finally in the `onEnd` event I call `isTap` to be sure the event on my child button is a simple tap event on this button.
This way I can still swipe and make my calendar scroll, but I can also tap on a single day to select it (swiping does not and must not select a day).

However I think exposing an `onEndWithOoptions` function would be nice and useful maybe for other people, what do you think?

**Comment by zwilias** [comment]
Happy to hear you found a way to make it work!

It seems like investing time in better documentation and examples for handling cases like yours is a more constructive idea than adding `onEndWithOoptions`, which adds the risk that people might overlook the possibility of handling it like your did.

Basically, I think doing something like this would work best:

```elm
type Msg = Touch Touch.Event | TouchUp Touch.Event | Click

update : Msg -> Model -> (Model, Cmd Msg)
update msg model =
    case msg of
        Touch event ->
            -- Record the event
            { model | gesture = Touch.record touch model.gesture }

        TouchUp event ->
            let
                gesture = Touch.record event model.gesture
            in
            if Touch.isTap gesture then
                -- handle as tap
            else
                -- handle as swipe

         Click ->
             -- It's a click

view : a -> Html Msg
view _ =
    div
        [ Touch.onStart Touch
        , Touch.onMove Touch
        , Touch.onEnd TouhUp
        , Html.Events.onClick Click
        ]
        [ text "Swipe or tap me, I can do the right thing" ]
```

I've tried to allude to that sort of setup in the documentation, but I should probably add a full and concrete example 🤔

**Comment by FabienHenon** [comment]
I think your documentation was fine, but maybe you should warn people about the `onClick` not triggered?
And also maybe telling them that if they want to handle multiple touch events (on different elements) they should have multiple instances of `Touch.Event` to handle each case

**Comment by zwilias** [comment]
> I think your documentation was fine, but maybe you should warn people about the onClick not triggered?

Yes, definitely, good point!

> And also maybe telling them that if they want to handle multiple touch events (on different elements) they should have multiple instances of Touch.Event to handle each case

To help prevent me from writing unhelpful documentation, can you clarify what you mean exactly?

---

Thanks for your patience in explaining your issue, this is really helpful: it can definitely guide me towards writing better documentation and will help guide further evolution of the API of the package :)

**Comment by FabienHenon** [comment]
Thank you for this package ;)

**Comment by FabienHenon** [comment]
> To help prevent me from writing unhelpful documentation, can you clarify what you mean exactly?

In the documentation, after explaining how to use your package I would add a point telling that these steps must be repeated for each gesture on different elements we want to handle.

For instance, let's say I want to swipe a div, and I want to tap on another div, then you should have 2 `Touch.Event` objects in your model to manage each event separately. Because one could think he can handle all the events he wants with the same object but handling a swipe on an element and a tap (or other gesture) on another element is not the same.

**Comment by zwilias** [comment]
I see. While you would definitely need different messages carrying a `Touch.Event`, I do think that having only a single `Touch.Gesture` state machine in your model _should_ work. This does assume that a well-behaved browser will always send a `touchstart` before a `touchend`, and would also fail for nested elements 🤔 

So I guess having an example where a tap event is used within a swipeable element would be a good idea; to show when it is required to have more than one `Touch.Gesture`. Thanks, that was extremely helpful :)

**Comment by FabienHenon** [comment]
Unfortunately I have another issue with `onEnd` and `preventDefault`.

I have a global element listening for `onEnd` events, and in its children I have a `Material.Button` from `Mdl` package. However this package is using `onClick` to listen for clicks on buttons.
My problem can globally be seen each time we have to use third party package with `onClick` events.

Do you have any idea how I can handle this without modifying `Material.Button` to listen for touches?
Some way to disable touch gesture in some child components? Or allowing `onClick` on some child elements?

**Comment by zwilias** [comment]
That's very interesting, thanks for the heads-up!

This is more than enough reason to add an `onEndNoPreventDefault`. If you feel like making a PR, that would be awesome. If not, I can get around it to, too :)

**Comment by FabienHenon** [comment]
Actually I forked your package to test a function like this and this is working (without an `onClick` event being fired after a swipe).

I created a function called `onEndWithOptions` which takes options as parameters.
What do you think about it?

**Comment by zwilias** [comment]
Sure, sounds good 👍

**Comment by FabienHenon** [comment]
Alright, I'll created the PR :)

**Comment by FabienHenon** [comment]
The PR has been created, I didn't bump the package version
